<?php

declare(strict_types=1);

namespace Pimcore\Bundle\ComparisonBundle\Feature\Command;

use Pimcore\Bundle\ComparisonBundle\Feature\Coverage\CoverageReport;
use Pimcore\Bundle\ComparisonBundle\Feature\FeatureRegistry;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Yaml\Yaml;

/**
 * Regenerates the `_state/registry/` artefacts: the derived truth about the bundle's feature state.
 * Nothing in `_state/` is authored — everything is regenerated by this command and
 * `git diff --exit-code`-guarded in CI, so no one can hand-improve it.
 */
#[AsCommand(
    name: 'comparison:features:state',
    description: 'Regenerate the _state/registry/ artefacts (features, coverage, spec-coverage, FEATURES.md).'
)]
final class FeatureStateCommand extends Command
{
    private const SPEC_ID_PATTERN = '/\b(?:FR-[A-Z]+-\d+|C-\d+|T-SEC-\d+[a-z]?|T-ARCH-\d+|T-FEAT-\d+|E2E-[A-Z]+-\d+)\b/';

    private const HEADER = "# GENERATED by `comparison:features:state` — do not edit. `git diff --exit-code` guards this.\n";

    public function __construct(private readonly FeatureRegistry $registry)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('coverage', null, InputOption::VALUE_REQUIRED, 'Path to coverage.json', 'var/comparison-feature-coverage.json')
            ->addOption('specs-dir', null, InputOption::VALUE_REQUIRED, 'Spec docs scanned for requirement ids', 'bundles/PimcoreComparisonBundle/_specs')
            ->addOption('out-dir', null, InputOption::VALUE_REQUIRED, 'Output directory', 'bundles/PimcoreComparisonBundle/_state/registry');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outDir = rtrim((string) $input->getOption('out-dir'), '/');
        @mkdir($outDir, 0777, true);

        $coverage = $this->loadCoverage((string) $input->getOption('coverage'));
        $rows = $this->registry->resolve($coverage);
        ksort($rows);

        // 1. features.yaml
        $features = [];
        foreach ($rows as $id => $row) {
            $features[$id] = [
                'group' => $row['decl']['group'],
                'name' => $row['decl']['name'],
                'description' => $row['decl']['description'],
                'declared' => $row['declared']->value,
                'effective' => $row['effective']->value,
                'overclaim' => $row['overclaim'],
                'unknown' => $row['unknown'],
                'openGaps' => $row['decl']['openGaps'],
                'specRefs' => $row['decl']['specRefs'],
                'dependsOn' => $row['decl']['dependsOn'],
                'since' => $row['decl']['since'],
                'backendOnly' => $row['decl']['backendOnly'],
                'declaredIn' => $row['decl']['declaredIn'],
                'phpunit' => $row['phpunit'],
                'playwright' => $row['playwright'],
            ];
        }
        $this->write($outDir . '/features.yaml', self::HEADER . Yaml::dump([
            'generator' => 'comparison:features:state',
            'coveragePresent' => $coverage->present,
            'violations' => $this->registry->violations($coverage),
            'features' => $features,
        ], 6, 2));

        // 2. coverage.yaml
        $this->write($outDir . '/coverage.yaml', self::HEADER . Yaml::dump([
            'present' => $coverage->present,
            'phpunit' => $this->coverageMap($rows, 'phpunit'),
            'playwright' => $this->coverageMap($rows, 'playwright'),
        ], 4, 2));

        // 3. spec-coverage.yaml
        $specIds = $this->scanSpecIds((string) $input->getOption('specs-dir'));
        $claimed = $this->registry->claimedSpecRefs();
        sort($claimed);
        $orphaned = array_values(array_diff($specIds, $claimed));
        $unknownClaims = array_values(array_diff($claimed, $specIds));
        $this->write($outDir . '/spec-coverage.yaml', self::HEADER . Yaml::dump([
            'specRequirementIds' => $specIds,
            'claimed' => $claimed,
            'orphaned' => $orphaned,
            'unknownClaims' => $unknownClaims,
            'summary' => [
                'total' => count($specIds),
                'claimed' => count(array_intersect($specIds, $claimed)),
                'orphaned' => count($orphaned),
            ],
        ], 4, 2));

        // 4. FEATURES.md
        $this->write($outDir . '/FEATURES.md', $this->featuresMarkdown($rows, $coverage));

        $io->success(sprintf('Regenerated %s: features.yaml, coverage.yaml, spec-coverage.yaml, FEATURES.md '
            . '(%d features, %d spec ids, %d orphaned).', $outDir, count($rows), count($specIds), count($orphaned)));

        $violations = $this->registry->violations($coverage);
        if ($violations !== []) {
            $io->warning(sprintf('%d overclaim/violation(s) recorded in features.yaml.', count($violations)));
        }

        return Command::SUCCESS;
    }

    private function coverageMap(array $rows, string $key): array
    {
        $map = [];
        foreach ($rows as $id => $row) {
            if ($row[$key]['passed'] > 0 || $row[$key]['failed'] > 0) {
                $map[$id] = $row[$key];
            }
        }

        return $map;
    }

    /** @return string[] sorted unique requirement ids found across the spec docs */
    private function scanSpecIds(string $specsDir): array
    {
        $ids = [];
        if (is_dir($specsDir)) {
            foreach (Finder::create()->files()->in($specsDir)->name('*.md') as $file) {
                if (preg_match_all(self::SPEC_ID_PATTERN, (string) file_get_contents($file->getRealPath()), $m)) {
                    foreach ($m[0] as $id) {
                        $ids[$id] = true;
                    }
                }
            }
        }
        $ids = array_keys($ids);
        sort($ids);

        return $ids;
    }

    private function featuresMarkdown(array $rows, CoverageReport $coverage): string
    {
        $lines = [
            '# Comparison features',
            '',
            '<!-- GENERATED by `comparison:features:state` — do not edit. `git diff --exit-code` guards this. -->',
            '',
            '| Feature | Group | Status | PHPUnit | Playwright | Gaps |',
            '|---|---|---|---|---|---|',
        ];
        foreach ($rows as $id => $row) {
            $status = $row['declared'] === $row['effective'] ? $row['effective']->value
                : sprintf('%s (claims %s)', $row['effective']->value, $row['declared']->value);
            $lines[] = sprintf('| `%s` | %s | %s | %d✓/%d✗ | %d✓/%d✗ | %s |',
                $id, $row['decl']['group'], $status,
                $row['phpunit']['passed'], $row['phpunit']['failed'],
                $row['playwright']['passed'], $row['playwright']['failed'],
                $row['decl']['openGaps'] === [] ? '—' : implode('; ', $row['decl']['openGaps']));
        }
        if (!$coverage->present) {
            $lines[] = '';
            $lines[] = '> No coverage report ingested — tested features are shown as unknown, not green.';
        }

        return implode("\n", $lines) . "\n";
    }

    private function loadCoverage(string $path): CoverageReport
    {
        if (!is_file($path)) {
            return CoverageReport::unknown();
        }
        $data = json_decode((string) file_get_contents($path), true);

        return is_array($data) ? CoverageReport::fromArray($data) : CoverageReport::unknown();
    }

    private function write(string $path, string $content): void
    {
        file_put_contents($path, $content);
    }
}
